### ISSUE TITLE
New email code

### ISSUE THREAD

**Issue by Flying39** [rockdevourer/borderlands#7]
Joypuke

https://imgur.com/4jQ3BAW

**Comment by rockdevourer** [comment]
Thank you! Currently, the "maintained" list of codes is being provided by the /r/borderlands3 discord server, via this link (this is just a link to the spreadsheet):

https://docs.google.com/spreadsheets/d/1QfwdILwVv19sKeveaBzZwhQLEOzmFwnOmMZsWLKwgg8/htmlview?usp=sharing&sle=true
