### ISSUE TITLE
New code lists 9/20

### ISSUE THREAD

**Issue by jcDunlop99** [rockdevourer/borderlands#8]
var EMAILS = [
    "2kLove",
	"ABCEASYAS123",
	"ALMOSTTHERE",
	"BL3ATE3",
	"BL3REVEAL",
	"BL3WELCOME",
	"BUILDURSQUAD",
	"CLAPTASTIC",
	"Dasherz",
	"DUCTTAPEMOD",
	"FIGHT4SANCTUARY",
	"FORTNITEXMAYHEM",
	"FRESHBOOTY",
	"HEYSUGAR",
	"ITSHERE",
	"JABBER",
	"LESSTHANTHREE",
	"LOOTLOOTLOOT",
	"MADSKILLZ",
	"MYMAIN",
	"ONTHEHUNT",
	"OVERCLOCKED",
	"OVERONEBILLION",
	"POWERUPEMAIL",
	"SOHAPPYTOGETHER",
	"Unblinkingeye",
	"PS4MAYHEM",
	"ALLBORDERLANDSALLDAY",
	"DONTFORGET",
	"THEBORDERLANDSSHOW",
	"JOYPUKE"
]

var CREATORS = [
    "PROFESSORBROMANVIP",
    "KINGGOTHALIONVIP",
    "PietSmietVIP",
    "JoltzDude139VIP",
    "JvtvVIP",
    "AdmiralbahrooVIP",
    "Ki11erSixVIP",
    "MitsuShowVIP",
    "TessachkaVIP",
    "LaraLoftVIP",
    "MitsuShowE3",
    "TessachkaE3",
    "EdEMonsterE3",
    "Joltzdude139E3",
    "Ki11ersixE3",
    "KingGothalionE3",
    "ProfessorBromanE3",
    "AdmiralBahrooE3",
    "dammit2hellE3",
    "NAYSYE3",
    "LUCKYBONEZE3",
    "GRIMMBONEZE3",
    "CohhVIP",
    "Cure4Kids",
    "GREGORONKH"
]

var VAULTS = [
    "WUBWUBWUB",
    "JOYPUKE",
    "LOADINGBAR",
    "IGNVIP",
    "Borderlands3vip",
    "TWITCHVIP",
    "GAMESPOTVIP",
    "FACEBOOKVIP",
    "SHACKNEWSVIP",
    "GAMEVIP",
    "WEGOTUBOO",
    "LOWCOSTCOSPLAYE3",
    "BORDERLANDSCOSPLAYE3",
    "ILOVEBAGUETTE",
    "BL3FREVENTVIP",
    "WHATCHUWANT",
    "MUSHYSNUGGLEBITES",
    "OOPS",
    "BORDERLENS",
    "Skagbait",
    "VIP-GUNWALL",
    "VIP-GIFTSHOP",
    "VIP-REDCHEST",
    "VIP-COV",
    "VIP-MOXXI",
    "VIP-ENVART",
    "VIP-CALYPSO",
    "VIP-CHARCONCEPT",
    "VIP-BOXCONCEPT",
    "VIP-PHOTOBOOTH",
    "BL3MUSEUMCOSPLAY",
    "3DJUEGOSVIP",
    "HALVERHAHN",
    "BRINGMEABUCKET",
    "MAYHEMPRIDE",
    "PWR2PLYRS",
    "THESEPRETZELSSUCK",
    "TINKABOUTIT",
    "LOOTSPLOSION",
    "BONERFART",
    "LETSMAKESOMEMAYHEM",
    "MAYHEM",
    "CRUMPOCALYPSE",
    "Childrenofthevault",
    "WACHSK4G",
    "JABBERKUMP3L",
    "D1G1KLON",
    "RA1LGUN",
    "5piderantcenturio",
    "Phasenkl4mmerung",
    "1ronbear",
    "Sntnl",
    "Phasenproj3ktion",
    "Ph4senschlag",
    "1CODE",
    "GODSDONTNEGOTIATE",
    "Ehrenmann",
    "TWOWEEKS",
    "VIP-PAXINIT",
    "VIP-PAXALAX",
    "VIP-SUPERPAX",
    "VIP-EATINGPAX",
    "JVMVIP",
    "VIP-LOOTPAX",
    "VIP-PAXSCAVENGER",
    "PAXSCAVENGER",
    "VIP-PAXATYA",
    "VIP-PAXATTACK",
    "VIP-TAKEITTOTHEPAX",
    "VIP-PAXTASTIC",
    "SMARTOYSVIP",
    "MEDIAMARKTVIP",
    "Bolvip",
    "GAMEMANIAVIP",
    "ALLYOURGAMESVIP",
    "NEDGAMEVIP",
    "YOURGAMEZONEVIP",
    "VIP-DEATHANDPAXES",
    "VIP-SMACKTHATPAX",
    "VIP-KEEPINGITPAX",
    "INTERTOYSVIP",
    "PLAYERONEVIP",
    "VIP-ANOTHERPAXPUN",
    "vip-paxagainstthewall",
    "SEVENDAYS",
    "AIRLEMAGVIP",
	"Dreamlandvip",
	"ITSBEEN"
]

**Comment by rockdevourer** [comment]
Thank you! Currently, the "maintained" list of codes is being provided by the /r/borderlands3 discord server, via this link (this is just a link to the spreadsheet):

https://docs.google.com/spreadsheets/d/1QfwdILwVv19sKeveaBzZwhQLEOzmFwnOmMZsWLKwgg8/htmlview?usp=sharing&sle=true
